# android
adb shell pm install-existing --user 0 com.android.documentsui
adb shell pm install-existing --user 0 com.android.browser
adb shell pm install-existing --user 0 com.android.soundrecorder
adb shell pm install-existing --user 0 com.android.mms
adb shell pm install-existing --user 0 com.android.calendar
adb shell pm install-existing --user 0 com.android.printspooler
adb shell pm install-existing --user 0 com.android.synccontact
adb shell pm install-existing --user 0 com.android.webview
adb shell pm install-existing --user 0 com.android.musicfx
adb shell pm install-existing --user 0 com.android.gallery3d
adb shell pm install-existing --user 0 com.android.emergency
adb shell pm install-existing --user 0 com.android.calculator2
adb shell pm install-existing --user 0 com.android.music
adb shell pm install-existing --user 0 com.android.deskclock
adb shell pm install-existing --user 0 com.android.quicksearchbox
adb shell pm install-existing --user 0 com.android.internal.systemui.navbar.threebutton
adb shell pm install-existing --user 0 com.android.cts.priv.ctsshim
adb shell pm install-existing --user 0 com.android.internal.display.cutout.emulation.corner
adb shell pm install-existing --user 0 com.android.internal.display.cutout.emulation.double
adb shell pm install-existing --user 0 com.android.stk
adb shell pm install-existing --user 0 com.android.providers.calendar
adb shell pm install-existing --user 0 com.android.providers.downloads.ui
# evenwell
adb shell pm install-existing --user 0 com.evenwell.fnotes
adb shell pm install-existing --user 0 com.evenwell.OTAUpdate
adb shell pm install-existing --user 0 com.evenwell.tmobile.vvm
# nuance
adb shell pm install-existing --user 0 com.nuance.voiceservice
adb shell pm install-existing --user 0 com.nuance.voiceclient
adb shell pm install-existing --user 0 com.nuance.accessibility
adb shell pm install-existing --user 0 com.nuance.talkback
# qualcomm
adb shell pm install-existing --user 0 com.qti.confuridialer
adb shell pm install-existing --user 0 com.qti.dpmserviceapp
adb shell pm install-existing --user 0 com.qti.qualcomm.datastatusnotification
adb shell pm install-existing --user 0 com.qti.service.colorservice
adb shell pm install-existing --user 0 com.qti.snapdragon.qdcm_ff
adb shell pm install-existing --user 0 com.qualcomm.atfwd
adb shell pm install-existing --user 0 com.qualcomm.embms
adb shell pm install-existing --user 0 com.qualcomm.location
adb shell pm install-existing --user 0 com.qualcomm.qti.qmmi
adb shell pm install-existing --user 0 com.qualcomm.location.XT.setup
# sonim
adb shell pm install-existing --user 0 com.sonim.kiosk
adb shell pm install-existing --user 0 com.sonim.scout
adb shell pm install-existing --user 0 com.sonim.logcollector
adb shell pm install-existing --user 0 com.sonim.vowifiauth
adb shell pm install-existing --user 0 com.sonim.exif
adb shell pm install-existing --user 0 com.sonim.gif
adb shell pm install-existing --user 0 com.sonim.camera
adb shell pm install-existing --user 0 com.sonim.backup
adb shell pm install-existing --user 0 com.sonim.ble.connect.xp8
adb shell pm install-existing --user 0 com.sonim.entitlement
adb shell pm install-existing --user 0 com.sonim.safeguard
adb shell pm install-existing --user 0 com.sonim.progtorch
adb shell pm install-existing --user 0 com.sonim.carrier
adb shell pm install-existing --user 0 com.sonim.launcher
adb shell pm install-existing --user 0 com.sonim.scout.stealthmode
adb shell pm install-existing --user 0 com.sonim.scout.callscreening
adb shell pm install-existing --user 0 com.sonim.scout.warranty
adb shell pm install-existing --user 0 com.sonim.scout.contact
adb shell pm install-existing --user 0 com.sonim.sonimcustomercare.ten
adb shell pm install-existing --user 0 com.sonim.scout.mdmhelper
adb shell pm install-existing --user 0 com.sonim.ble.connect.xp8
adb shell pm install-existing --user 0 com.sonimtech.spcc
adb shell pm install-existing --user 0 com.sonimtech.setupwizard.ten
adb shell pm install-existing --user 0 com.sonimtech.sonimupdater
adb shell pm install-existing --user 0 com.splashtop.streamer.platform.sonim.b
adb shell pm install-existing --user 0 com.splashtop.sos.sonim
# sprint
adb shell pm install-existing --user 0 com.sprint.ms.cdm
adb shell pm install-existing --user 0 com.sprint.w.installer
adb shell pm install-existing --user 0 com.sprint.sdcplus
# misc.
adb shell pm install-existing --user 0 com.caf.fmradio
adb shell pm install-existing --user 0 com.fih.savetime
adb shell pm install-existing --user 0 com.borqs.easervice
adb shell pm install-existing --user 0 com.skyhook.blp
