adb shell pm uninstall -k --user 0 com.android.documentsui
adb shell pm uninstall -k --user 0 com.android.browser
adb shell pm uninstall -k --user 0 com.android.soundrecorder
adb shell pm uninstall -k --user 0 com.android.mms
adb shell pm uninstall -k --user 0 com.android.calendar
adb shell pm uninstall -k --user 0 com.android.printspooler
adb shell pm uninstall -k --user 0 com.android.synccontact
adb shell pm uninstall -k --user 0 com.android.webview
adb shell pm uninstall -k --user 0 com.android.musicfx
adb shell pm uninstall -k --user 0 com.android.gallery3d
adb shell pm uninstall -k --user 0 com.android.emergency
adb shell pm uninstall -k --user 0 com.android.calculator2
adb shell pm uninstall -k --user 0 com.android.music
adb shell pm uninstall -k --user 0 com.android.deskclock
adb shell pm uninstall -k --user 0 com.android.quicksearchbox
adb shell pm uninstall -k --user 0 com.android.internal.systemui.navbar.threebutton
adb shell pm uninstall -k --user 0 com.android.cts.priv.ctsshim
adb shell pm uninstall -k --user 0 com.android.internal.display.cutout.emulation.corner
adb shell pm uninstall -k --user 0 com.android.internal.display.cutout.emulation.double
adb shell pm uninstall -k --user 0 com.android.stk
adb shell pm uninstall -k --user 0 com.android.providers.calendar
adb shell pm uninstall -k --user 0 com.android.providers.downloads.ui
